### ISSUE TITLE
Intermittent "RemoteAccessException: Could not access HTTP invoker remote service - Connection reset" when creating and running a test suite by API 

### ISSUE THREAD

**Issue by rachel-orti** [ODMDev/odm-ondocker#98] opened 2017-11-15 16:20 UTC
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [http://vtt-odm125.fr.eurolabs.ibm.com:30105/decisioncenter/remoting/session?__dcsid=1db86d384ac082f6ac81cc0e38015f28]; nested exception is java.net.SocketException: Connection reset	at java.net.SocketInputStream.read(SocketInputStream.java:220)	at java.net.SocketInputStream.read(SocketInputStream.java:152)	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)	at org.springframework.remoting.httpinvoker.HttpComponentsHttpInvokerRequestExecutor.executeHttpPost(HttpComponentsHttpInvokerRequestExecutor.java:354)	at org.springframework.remoting.httpinvoker.HttpComponentsHttpInvokerRequestExecutor.doExecuteRequest(HttpComponentsHttpInvokerRequestExecutor.java:245)	at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.executeRequest(AbstractHttpInvokerRequestExecutor.java:136)	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:202)	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:184)	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:150)	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)	at com.sun.proxy.$Proxy10.getElementDetailsForThisHandle(Unknown Source)	at ilog.rules.teamserver.model.impl.IlrAbstractSession.getElementDetails(IlrAbstractSession.java:1123)	at ilog.rules.teamserver.model.impl.IlrAbstractCachingSession.getElementDetails(IlrAbstractCachingSession.java:88)	at ilog.rules.teamserver.model.impl.IlrAbstractSession.getElementDetails(IlrAbstractSession.java:1110)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)	at java.lang.reflect.Method.invoke(Method.java:507)	at ilog.rules.teamserver.client.IlrSessionInvocationHandler.invoke(IlrSessionInvocationHandler.java:43)	at com.sun.proxy.$Proxy11.getElementDetails(Unknown Source)	at com.ibm.odm.cloud.mat.tests.remoteconnection.RemoteConnectionBase.createAndRunTestSuite(RemoteConnectionBase.java:518)	at com.ibm.odm.cloud.mat.tests.remoteconnection.DecisionCenterTestSuiteTest.testCreateAndRunDecisionCenterTestSuite(DecisionCenterTestSuiteTest.java:27)
--

**Comment by rachel-orti** [comment] 2017-11-15 16:22
Certainly related to #47.

**Comment by mmouly** [comment] 2017-11-15 16:51
It's a duplicate of #47. We can close it and only keep  #47 .

**Comment by mmouly** [comment] 2017-11-17 08:39
reopen it as it's not the same issue.
Looks like remote session connection is lost.
Perhaps this test takes more time than others ?
have a look at it's possible to catch the error and try to reconnect

**Comment by mmouly** [comment] 2017-11-22 09:34
Shilpa changed a little bit the test code so the issue must appear less frequently.
Will reopen it if it happen again.

**Closed by mmouly** 2017-11-22 09:34 UTC
